<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_xxxx</name>
   <tag></tag>
   <elementGuidId>5a497851-3705-40d5-a4ed-cc226b197877</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;perspectiveTabContainer_tabsBC_tab0_editor&quot;)/div[@class=&quot;textview sce sce-sas&quot;]/div[7]/div[@class=&quot;textviewContent&quot;]/div[4]/span[@class=&quot;cards-data&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>xxxx</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cards-data</value>
   </webElementProperties>
</WebElementEntity>
